name: Auto merge to develop
on:
  push:
    branches:
      - 'release/GitgubAction'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Merge and Push
      run: |
        git checkout develop
        git merge --no-ff 'release/GitgubAction'
        git push origin develop
