# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  push:
    branches:
      - '*release*'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Git
      run: |
        git config --global user.email "joony300@gmail.com"
        git config --global user.name "Jimmy"
    - name: Merge and Push
      run: |
        git checkout develop
        git merge --no-ff ${GITHUB_REF#refs/heads/}
        git push origin develop
